# docker-compose.yml (optional helper)
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend/data:/app/data
      - ./backend/embeddings:/app/embeddings
      - ./backend/tac_projector_vit5p_best.pt:/app/tac_projector_vit5p_best.pt
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    depends_on: [backend]
